### PR TITLE
Fix issue #20

### PR DESCRIPTION
**Pull request by boskisam**
Fix the issue with snap-installed helm. Tried with 
ubuntu: 20.04
bash: 5.0.17(1)
helm: version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

### CODE REVIEW

**Comment by boskisam** [comment]
Resolves @ #20

**Review by myishay — COMMENTED** [review]
@boskisam Thank you for your contribution!

I like the changes you made! As you mentioned in the issue, we prefer to have the chart name as temp file name for debug purposes, so I think it is a good idea to use datree with no filename if we cannot create a temp file with the chart name.
I do think the condition you made could be a bit more generic; for example checking if the created temp file could be written\read by the OS and if not, rollback to the `else` statement you wrote.

WDYT?

**Comment by myishay** [comment]
ping @boskisam 😊 
Did you have a chance to look at my comment?

**Comment by boskisam** [comment]
Hi, will have a look into it after Christmas, hadn't had a chance to work on it since starting the PR.

**Comment by myishay** [comment]
> Hi @myishay, hadn't had a chance to work on it since starting the PR.
> 
> The problem is - file at system /tmp can be rw by the OS, and any app that uses OS filesystem. Problem is that HELM as a snap has its own **/tmp** directory. I think checking if helm is installed as snap is best option for now. Checking file permissions wouldn't address the issue, since it's not a problem of file or dir permissions, but with snap handling the /tmp folder.

What about preforming a semi try/catch mechanism?
If any error occurred when creating the temp yaml or reading from it, rollback to the `else` statement you wrote.

**Comment by myishay** [comment]
Closing this due to inactivity.

@boskisam Thank you for your time!

**Pull request closed without merging**
